version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/core"
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "/commandeer"
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "/voice"
    schedule:
      interval: "daily" 
 